### PR TITLE
updates sha256_db

### PR DESCRIPTION
**Pull request by ghost**
updates sha256 signatures, verified from VirusTotal

### CODE REVIEW

**Comment by ghost** [comment]
ASAP, I will add new signatures to sha256_db

**Comment by HydraDragonAntivirus** [comment]
Thanks for second update. I recommend you to use ssdeep or tlsh.  tlsh is best.

**Comment by ghost** [comment]
have you got a tlsh_db file to fill?

**Comment by HydraDragonAntivirus** [comment]
I have already tlsh_db but generated from malwarebazaar.

**Pull request merged**
